apiVersion: v1
kind: Service
metadata: 
  name: my-app-service
  labels: 
    app: bootcamp-my-app
    tier: frontend
spec:
  selector:
    app: bootcamp-my-app
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer